# Build settings

markdown: kramdown
permalink: pretty

port: 8000
baseurl: ""
url: "http://ramunasnognys.github.io" 

include: ['_includes/pages',]
exclude: ['the_design.psd',
          'package.json',
          'src', 
          'node_modules']

sass:
  sass_dir: assets/css
  style: :nested

# User settings
username: Ramūnas Nognys
user_description: Bicycle rights irony actually neutra typewriter lyft. Man bun taxidermy put a bird on it, umami yr ramps pop-up ugh bushwick chia lo-fi. Occupy bitters pour-over snackwave you probably haven't heard of them small batch. Cornhole mustache man bun letterpress echo park VHS.
user_title: Junior Software Developer
email: ramunas.nognys@gmail.com
twitter_username: lorem_ipsum
github_username:  https://github.com/ramunasnognys
gplus_username:  https://plus.google.com/104353493900718561674
